import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from '@/components/ui/sonner';
import { TooltipProvider } from '@/components/ui/tooltip';
import { fontMono, fontSans } from '@/fonts/font';
import { cn } from '@/lib/utils';
import { Metadata } from 'next';
import { PropsWithChildren } from 'react';
import './globals.css';

export const metadata: Metadata = {
    title: {
        default: '欢迎 - WingLab直播',
        template: '%s - WingLab直播',
    },
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html
            lang="zh"
            suppressHydrationWarning
            className={cn(fontSans.variable, fontMono.variable)}
        >
            <body className="flex min-h-full flex-col">
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <TooltipProvider>
                        {children}
                        <Toaster position="top-right" />
                    </TooltipProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
