import { EchoProvider } from '@/components/provider/echo-provider';
import { ProgressProvider } from '@/components/provider/progress-provider';
import { ThemeProvider } from '@/components/provider/theme-provider';
import { UserProvider } from '@/components/provider/user-provider';
import { Toaster } from '@/components/shadcn/sonner';
import { TooltipProvider } from '@/components/shadcn/tooltip';
import { fontMono, fontSans } from '@/fonts/font';
import { cn } from '@/lib/utils';
import { profileShow } from '@/service/api/auth';
import { Metadata } from 'next';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { PropsWithChildren } from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: {
    default: '欢迎 - WingLab直播',
    template: '%s - WingLab直播',
  },
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: PropsWithChildren) {
  const initialUser = await profileShow();

  return (
    <html lang="zh" suppressHydrationWarning className={cn(fontSans.variable, fontMono.variable)}>
      <body className="flex min-h-full flex-col">
        <NuqsAdapter>
          <ProgressProvider color="#9ae600" options={{ showSpinner: false }}>
            <UserProvider initialUser={initialUser}>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <TooltipProvider>
                  <EchoProvider>{children}</EchoProvider>
                  <Toaster position="top-right" />
                </TooltipProvider>
              </ThemeProvider>
            </UserProvider>
          </ProgressProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
